"""add gsc countries devices

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-08 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsc_countries',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('date_metric', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gsc_country_name', 'gsc_countries', ['country'], unique=False)
    op.create_index('idx_gsc_country_site_date', 'gsc_countries', ['website_id', 'date_metric'], unique=False)
    op.create_index(op.f('ix_gsc_countries_date_metric'), 'gsc_countries', ['date_metric'], unique=False)
    op.create_index(op.f('ix_gsc_countries_website_id'), 'gsc_countries', ['website_id'], unique=False)
    
    op.create_table('gsc_devices',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('device', sa.String(length=100), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('date_metric', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gsc_device_name', 'gsc_devices', ['device'], unique=False)
    op.create_index('idx_gsc_device_site_date', 'gsc_devices', ['website_id', 'date_metric'], unique=False)
    op.create_index(op.f('ix_gsc_devices_date_metric'), 'gsc_devices', ['date_metric'], unique=False)
    op.create_index(op.f('ix_gsc_devices_website_id'), 'gsc_devices', ['website_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gsc_devices_website_id'), table_name='gsc_devices')
    op.drop_index(op.f('ix_gsc_devices_date_metric'), table_name='gsc_devices')
    op.drop_index('idx_gsc_device_site_date', table_name='gsc_devices')
    op.drop_index('idx_gsc_device_name', table_name='gsc_devices')
    op.drop_table('gsc_devices')
    
    op.drop_index(op.f('ix_gsc_countries_website_id'), table_name='gsc_countries')
    op.drop_index(op.f('ix_gsc_countries_date_metric'), table_name='gsc_countries')
    op.drop_index('idx_gsc_country_site_date', table_name='gsc_countries')
    op.drop_index('idx_gsc_country_name', table_name='gsc_countries')
    op.drop_table('gsc_countries')
    # ### end Alembic commands ###
